name: Build image

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: WTF
        shell: cmd
        run: dir
      - name: Docker build
        shell: cmd
        run: docker build . --tag mywintest
